import javax.swing.*;
import javax.swing.event.DocumentEvent;
import javax.swing.event.DocumentListener;
import java.awt.*;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;

/**
 * Created by Marco on 14.04.2014.
 */
public class MainWindow2 extends JFrame {
    private JButton clickButton;
    private JPanel rootPanel;
    private JTextField textField1;
    private JLabel eMailLabel;
    private JButton saveImageButton;
    private StringImage eMailImage;

    public MainWindow2() {
        super("Email to PMG Converter");
        pack();
        setContentPane(rootPanel);
        setDefaultCloseOperation(WindowConstants.EXIT_ON_CLOSE);
        setSize(650, 500);

        this.eMailImage = new StringImage();
        eMailLabel.setIcon(new ImageIcon(eMailImage.getBufferedImage()));

        setVisible(true);


        //this.eMailImage.setString("teststring");

        clickButton.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                //JOptionPane.showConfirmDialog(MainWindow.this, "MyDialog");
                eMailImage.setString(textField1.getText());
                eMailLabel.setIcon(new ImageIcon(eMailImage.getBufferedImage()));
            }
        });
        saveImageButton.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                eMailImage.saveImage();
            }
        });

        textField1.getDocument().addDocumentListener(new DocumentListener() {
            @Override
            public void insertUpdate(DocumentEvent e) {
                eMailImage.setString(textField1.getText());
                eMailLabel.setIcon(new ImageIcon(eMailImage.getBufferedImage()));
            }

            @Override
            public void removeUpdate(DocumentEvent e) {
                eMailImage.setString(textField1.getText());
                eMailLabel.setIcon(new ImageIcon(eMailImage.getBufferedImage()));
            }

            @Override
            public void changedUpdate(DocumentEvent e) {
                eMailImage.setString(textField1.getText());
                eMailLabel.setIcon(new ImageIcon(eMailImage.getBufferedImage()));
            }
        });

    }

    public static void main(String[] args) {
        MainWindow2 mainWindow = new MainWindow2();


    }

    {
// GUI initializer generated by IntelliJ IDEA GUI Designer
// >>> IMPORTANT!! <<<
// DO NOT EDIT OR ADD ANY CODE HERE!
        $$$setupUI$$$();
    }

    /**
     * Method generated by IntelliJ IDEA GUI Designer
     * >>> IMPORTANT!! <<<
     * DO NOT edit this method OR call it in your code!
     *
     * @noinspection ALL
     */
    private void $$$setupUI$$$() {
        rootPanel = new JPanel();
        rootPanel.setLayout(new BorderLayout(0, 0));
        clickButton = new JButton();
        clickButton.setText("Button");
        rootPanel.add(clickButton, BorderLayout.NORTH);
        textField1 = new JTextField();
        rootPanel.add(textField1, BorderLayout.CENTER);
        eMailLabel = new JLabel();
        eMailLabel.setText("Label");
        rootPanel.add(eMailLabel, BorderLayout.SOUTH);
        saveImageButton = new JButton();
        saveImageButton.setText("Button");
        rootPanel.add(saveImageButton, BorderLayout.EAST);
    }

    /**
     * @noinspection ALL
     */
    public JComponent $$$getRootComponent$$$() {
        return rootPanel;
    }
}